/*
 * modelParser.h
 *
 *  Created on: 22-Sep-2021
 *      Author: amit
 */

#ifndef MODELPARSER_MODELPARSER_H_
#define MODELPARSER_MODELPARSER_H_

#include "../hybridautomata/hybridAutomata.h"
#include "../commandLineParser/user_inputs.h"

// NOT USED /*
// NOT USED  * Reads a model file generated by the Learning algorithm and creates an object of hybridAutomata, when the learning algorithm implements One-Versus-One for inferring hyperplane to represent guard
// NOT USED  */
// NOT USED void modelParser_OneVersusOne(hybridAutomata::ptr &H, user_inputs::ptr &user, intermediateResult::ptr &intermediate);
// NOT USED 
// NOT USED /*
// NOT USED  * Reads a model file generated by the Learning algorithm and creates an object of hybridAutomata, when the learning algorithm implements One-Versus-Rest for inferring hyperplane to represent guard
// NOT USED  */
// NOT USED 
// NOT USED void modelParser(hybridAutomata::ptr &H, user_inputs::ptr &user, intermediateResult::ptr &intermediate);


/*
 * The above two parser function is now replaced by new approach. Uses connecting point and human annotation for Reset function
 */
void ha_model_parser(hybridAutomata::ptr &H, user_inputs::ptr &user
                     // , intermediateResult::ptr &intermediate  (not used)
                     );

#endif /* MODELPARSER_MODELPARSER_H_ */
